footerpanel <- fluidRow(
  column(width = 3,
         dropdown(label = '标题修改',
                  style = 'fill',
                  up =T,
                  icon = icon('tags'),
                  width = '400px',
                  size = 'sm',
                  textInput(inputId = 'text_title',
                            label = p('标题',
                                      labs_options_input(inputId = 'text_title',
                                                         defaults = get_labs_defaults(name = 'title'))),
                            width = '310px',
                            value = '流行曲线'),
                  textInput(inputId = 'text_subtitle',
                            label = p('副标题',
                                      labs_options_input(inputId = 'text_subtitle',
                                                         defaults = get_labs_defaults(name = 'subtitle'))),
                            width = '310px',
                            value = "CTModelling"),
                  textInput(inputId = 'text_legend',
                            label = p('图例设置',
                                      labs_options_input(inputId = 'text_legend',
                                                         defaults = get_labs_defaults(name = 'legend'))),
                            placeholder = '图例标题',
                            width = '310px'),
                  textInput(inputId = 'text_xlabs',
                            label = p('X轴标题',
                                      labs_options_input(inputId = 'text_xlabs',
                                                         defaults = get_labs_defaults(name = 'x'))),
                            value = '发病日期',
                            width = '310px'),
                  h4("日期显示设置"),
                  tags$div(
                    style = "display: inline-block;vertical-align:top; width: 100px; right: 20px",
                    pickerInput(inputId = "other_date_format",
                                label = "格式",
                                selected = "%m-%d\n%Y",
                                choices = list(
                                  "2019年12月31日" = "%Y年%m月%d日",
                                  "2019-12-31" = "%Y-%m-%d",
                                  "2019/12/31" = "%Y/%m/%d",
                                  "19年12月31日" = "%y年%m月%d日",
                                  "19-12-31" = "%y-%m-%d",
                                  "19/12/31" = "%y/%m/%d",
                                  "12月31日" = "%m月%d日",
                                  "12-31" = "%m-%d",
                                  "12/31" = "%m/%d",
                                  "2019年12月" = "%Y年%m月",
                                  "2019-12" = "%Y-%m",
                                  "2019/12" = "%Y/%m",
                                  "12月" = "%m月",
                                  "12" = "%m",
                                  "31" = "%d",
                                  "12月31日<换行>2019年" = "%m月%d日\n%Y年",
                                  "12月<换行>2019年" = "%m月\n%Y年",
                                  "12-31<换行>2019" = "%m-%d\n%Y",
                                  "12/31<换行>2019" = "%m/%d\n%Y",
                                  "31日<换行>19年12月" = "%d日\n%Y年%m月",
                                  "31日<换行>12月" = "%d日\n%m月"
                                ))
                  ),
                  div(style="display: inline-block;vertical-align:top; width: 10px;",HTML("<br>")),
                  tags$div(
                    style = "display: inline-block;vertical-align:top; width: 100px; right: 20px",
                    pickerInput(inputId = "other_date_facet",
                                label = "分级",
                                selected = "无",
                                choices = list(
                                  "无" = 'No',
                                  "年" = "Year",
                                  "季" = "Quarter",
                                  "月" = "Month",
                                  "年-月" = "Year-Month",
                                  "年|月" = "YearandMonth"
                                ))
                  ),
                  div(style="display: inline-block;vertical-align:top; width: 10px;",HTML("<br>")),
                  tags$div(
                    style = "display: inline-block;vertical-align:top; width: 100px; right: 20px",
                    pickerInput(inputId = "other_date_breaks",
                                label = "显示间隔",
                                choices = list(
                                  "每天" = "day",
                                  "每周" = "week",
                                  "每2周" = "2 weeks",
                                  "每月" = "month",
                                  "每季" = "4 months",
                                  "每半年" = "6 months",
                                  "每年" = "year"
                                )
                    )),
                  div(style="display: inline-block;vertical-align:top; width: 10px;",HTML("<br>")),
                  tags$br(),
                  tags$div(
                    style = "display: inline-block;vertical-align:top; width: 100px;",
                    numericInput(inputId = "text_x_angle",
                                 label = "显示角度",
                                 min = 0,
                                 max = 90,
                                 value = 0
                    )),
                  div(style="display: inline-block;vertical-align:top; width: 10px;",HTML("<br>")),
                  tags$div(
                    style = "display: inline-block;vertical-align:top; width: 100px; right: 20px",
                    numericInput(inputId = "scale_date_1",
                                label = "左侧调整(天)",
                                min = 0,
                                max = 365,
                                value = 0,
                                step = 1)
                  ),
                  div(style="display: inline-block;vertical-align:top; width: 10px;",HTML("<br>")),
                  tags$div(
                    style = "display: inline-block;vertical-align:top; width: 100px; right: 20px",
                    numericInput(inputId = "scale_date_2",
                                 label = "右侧调整(天)",
                                 min = 0,
                                 max = 365,
                                 value = 0,
                                 step = 1)
                  ),
                  textInput(input = 'text_ylabs',
                            label = p('Y轴标题',
                                      labs_options_input(inputId = 'text_ylabs',
                                                         defaults = get_labs_defaults(name = 'y'))),
                            value = '病例数',
                            width = '310px'),
                  textInput(input = 'text_caption',
                            label = p('注释',
                                      labs_options_input(inputId = 'text_caption',
                                                         defaults = get_labs_defaults(name = 'caption'))),
                            value = 'CTModelling',
                            width = '310px'),
                  textInput(input = 'text_normal',
                            label = p('其他文字',
                                      labs_options_input(inputId = 'text_normal',
                                                         defaults = get_labs_defaults(name = 'normal'))),
                            value = 'CTModelling',
                            width = '310px')
         )
  ),
  column(width = 3,
         dropdown(label = '颜色修改',
                  style = 'fill',
                  up =T,
                  icon = icon('palette'),
                  width = '400px',
                  size = 'sm',
                  pickerOpts = list(container = "body"),
                  palettePicker(
                    inputId = "color_pal", 
                    label = HTML('<span style="float:left;"><b>选择配色方案</b></span>
                                             <span style="position: absolute; right:30px;">
                                             <input id="color_pal_reverse" type="checkbox"/>倒置调色板？</span>'),
                    width = '370px',
                    textColor = textColor,
                    choices = choices,
                    selected = 'NPG'
                  ),
                  tags$div(
                    tags$b("自定义颜色"),
                    uiOutput(outputId = "color_manual")
                  ),
                  tags$br(),
                  pickerInput(inputId = "color_theme",
                              label = "绘图主题",
                              select = "classic",
                              choices = list(
                                "classic" = "theme_classic",
                                "gray" = "theme_gray",
                                "bw" = "theme_bw",
                                "linedraw" = "theme_linedraw",
                                "light" = "theme_light",
                                "dark" = "theme_dark",
                                "minimal" = "theme_minimal",
                                "void" = "theme_void"
                              ))
         )
  ),
  column(width = 3,
         dropdown(label = '数据筛选',
                  style = 'fill',
                  up =T,
                  icon = icon('database'),
                  width = '400px',
                  size = 'sm',
                  pickerOpts = list(container = "body"),
                  filter_data_ui("filter_data", max_height = "650px")
         )
  ),
  column(width = 3,
         dropdown(label = '其他',
                  style = 'fill',
                  up =T,
                  icon = icon('eject'),
                  width = '400px',
                  size = 'sm',
                  right = T,
                  pickerOpts = list(container = "body"),
                  column(width = 8,
                         awesomeRadio(inputId = 'other_bar_position',
                                      label = '柱图位置',
                                      width = '370px',
                                      selected = "stack",
                                      inline = TRUE,
                                      choices = list(
                                        "簇状" = "dodge",
                                        "堆积" = "stack",
                                        "百分比" = "fill"
                                      ))
                         ),
                  column(width = 4,
                         prettyCheckbox(inputId = 'other_bar_border',
                                        label = '图示每个病例',
                                        value = TRUE,
                                        status = "danger",
                                        shape = "curve")),
                  column(width = 12,
                         tags$b("边框颜色&宽度"),
                         tags$br(),
                         tags$div(style = "display: inline-block;vertical-align:top; width: 50px;",
                                  colorPickr(inputId = "other_bar_color",
                                             selected = "black",
                                             label = NULL,
                                             theme = "classic",
                                             width = '50px',
                                             useAsButton = TRUE,
                                             update = "save",
                                             interaction = list(
                                               hex = FALSE,
                                               rgba = FALSE,
                                               input = TRUE,
                                               save = TRUE,
                                               clear = FALSE
                                             ))),
                         tags$div(style = "display: inline-block;vertical-align:top; width: 100px;",
                                  numericInput(inputId = "other_bar_size",
                                               label = NULL,
                                               min = 0,
                                               max = 2,
                                               step = 0.1,
                                               value = 0.3))
                         ),
                  column(width = 12,
                         sliderInput(inputId = "other_bar_width",
                                     label = '间距',
                                     min = 0,
                                     max = 1,
                                     sep = 0.01,
                                     value = 1))
                  
         )
  )
  # HTML('<p class="copy-footer-29 text-center">Copyright 厦门大学公共卫生学院流行病学课题组 <br> 备案号：<a href="https://beian.miit.gov.cn/" target="_blank">闽ICP备2021008642号-1</a></p>')
)